// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using microbloom.Data;

#nullable disable

namespace microbloom.Migrations
{
    [DbContext(typeof(KariyerDBContext))]
    [Migration("20251109005545_AddRealContentData")]
    partial class AddRealContentData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("microbloom.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("microbloom.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Global teknoloji lideri.",
                            LogoUrl = "google.png",
                            Name = "Google"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Yazılım ve bulut çözümleri.",
                            LogoUrl = "microsoft.png",
                            Name = "Microsoft"
                        });
                });

            modelBuilder.Entity("microbloom.Entities.ContentArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentCategoryId");

                    b.ToTable("ContentArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "# Üniversite Seçimi Rehberi\r\n\r\nÜniversite seçimi, hayatınızın en önemli kararlarından biridir. İşte doğru tercih yapmanız için ipuçları:\r\n\r\n## 1. Bölüm Seçimi\r\n- İlgi alanlarınızı ve yeteneklerinizi değerlendirin\r\n- Bölümün kariyer olanaklarını araştırın\r\n- Sektördeki iş imkanlarını inceleyin\r\n\r\n## 2. Üniversite Kriterleri\r\n- Akademik kadro kalitesi\r\n- Kampüs imkanları ve sosyal aktiviteler\r\n- Uluslararası değişim programları\r\n- Mezun memnuniyeti ve kariyer desteği\r\n\r\n## 3. Şehir Seçimi\r\n- Yaşam maliyeti\r\n- Kültürel ve sosyal olanaklar\r\n- İş bulma imkanları\r\n- Ailenize uzaklık\r\n\r\n## 4. Taban Puan ve Sıralama\r\n- Gerçekçi hedefler belirleyin\r\n- Yedek tercihlerinizi mutlaka doldurun\r\n- Önceki yılların yerleştirme puanlarını inceleyin",
                            ContentCategoryId = 1,
                            Slug = "universite-secimi-rehberi",
                            Summary = "Üniversite seçerken nelere dikkat etmelisiniz? Şehir, bölüm, taban puan ve kariyer hedeflerinize göre doğru tercih nasıl yapılır?",
                            Title = "Üniversite Seçimi Rehberi"
                        },
                        new
                        {
                            Id = 2,
                            Content = "# Mühendislik Bölümleri Rehberi\r\n\r\n## Bilgisayar Mühendisliği\r\nYazılım geliştirme, veri bilimi, yapay zeka gibi alanlarda çalışma fırsatı sunar.\r\n\r\n**Kariyer Alanları:**\r\n- Yazılım Geliştirici\r\n- Veri Analisti / Data Scientist\r\n- Sistem Mimarı\r\n- DevOps Mühendisi\r\n\r\n**Başlangıç Maaşları:** 25.000 - 40.000 TL\r\n\r\n## Elektrik-Elektronik Mühendisliği\r\nElektronik sistemler, güç sistemleri, telekomünikasyon alanlarında uzmanlaşma.\r\n\r\n**Kariyer Alanları:**\r\n- Elektronik Tasarım Mühendisi\r\n- Enerji Sistemleri Uzmanı\r\n- Telekomünikasyon Mühendisi\r\n\r\n## Endüstri Mühendisliği\r\nÜretim süreçlerinin optimizasyonu, lojistik ve proje yönetimi.\r\n\r\n**Kariyer Alanları:**\r\n- Proje Yöneticisi\r\n- Lojistik Uzmanı\r\n- Süreç Geliştirme Mühendisi",
                            ContentCategoryId = 1,
                            Slug = "bolum-rehberi-muhendislik",
                            Summary = "Mühendislik bölümleri hakkında her şey: Hangi bölüm size uygun? Kariyer olanakları neler? Mezuniyet sonrası ne yapabilirsiniz?",
                            Title = "Bölüm Rehberi: Mühendislik"
                        },
                        new
                        {
                            Id = 3,
                            Content = "# Burs ve Mali Destek Rehberi\r\n\r\n## Devlet Bursu\r\n- YÖK bursu\r\n- Kredi Yurtlar Kurumu (KYK)\r\n- Başarı bursu\r\n\r\n## Özel Kuruluş Bursları\r\n- Vakıf üniversiteleri tam burs programları\r\n- Özel sektör şirket bursları (TÜBİTAK, TÜSİAD)\r\n- Belediye bursları\r\n\r\n## Başvuru İpuçları\r\n1. Başvuru tarihlerini takip edin\r\n2. Gereken belgeleri önceden hazırlayın\r\n3. Motivasyon mektubunuza özen gösterin\r\n4. Birden fazla burs programına başvurun\r\n\r\n## Önemli Linkler\r\n- turkiye.gov.tr/kyk-ogrenci-kredisi\r\n- yok.gov.tr",
                            ContentCategoryId = 1,
                            Slug = "burs-mali-destek",
                            Summary = "Üniversite eğitiminiz için burs ve mali destek alma yolları. Hangi kuruluşlar burs veriyor? Başvuru şartları neler?",
                            Title = "Burs ve Mali Destek İmkanları"
                        },
                        new
                        {
                            Id = 4,
                            Content = "# CV Hazırlama Rehberi\r\n\r\n## CV'de Olması Gerekenler\r\n\r\n### 1. Kişisel Bilgiler\r\n- Ad Soyad\r\n- İletişim Bilgileri (Telefon, E-posta)\r\n- LinkedIn Profili\r\n- GitHub (yazılımcılar için)\r\n\r\n### 2. Özet\r\n2-3 cümlelik kısa bir özet ile kendinizi tanıtın.\r\n\r\n**Örnek:** \"Bilgisayar Mühendisliği mezunu, 2 yıllık web geliştirme deneyimi. React ve Node.js teknolojilerinde uzman.\"\r\n\r\n### 3. Eğitim\r\n- Üniversite adı ve bölüm\r\n- Mezuniyet tarihi\r\n- Not ortalaması (3.00 üzerindeyse)\r\n\r\n### 4. İş Deneyimi\r\n- Şirket adı ve pozisyon\r\n- Çalışma tarihleri\r\n- Görev ve başarılarınız\r\n- Kullandığınız teknolojiler\r\n\r\n### 5. Projeler\r\n- Kişisel veya okul projeleri\r\n- Açık kaynak katkılarınız\r\n\r\n### 6. Beceriler\r\n- Programlama dilleri\r\n- Araçlar ve teknolojiler\r\n- Yabancı dil seviyeleri\r\n\r\n## CV Hazırlama İpuçları\r\n- Maksimum 2 sayfa olmalı\r\n- Özgeçmişinizi her pozisyon için özelleştirin\r\n- Somut başarılarınızı sayılarla destekleyin\r\n- Yazım hatalarından kaçının",
                            ContentCategoryId = 2,
                            Slug = "cv-hazirlama-rehberi",
                            Summary = "Profesyonel bir CV nasıl hazırlanır? İşverenin dikkatini çekecek CV örnekleri ve ipuçları.",
                            Title = "CV Hazırlama Rehberi"
                        },
                        new
                        {
                            Id = 5,
                            Content = "# İş Görüşmesine Hazırlık\r\n\r\n## Görüşme Öncesi\r\n1. Şirket hakkında araştırma yapın\r\n2. Pozisyon tanımını detaylı inceleyin\r\n3. Kendinizi tanıtma pratiği yapın\r\n4. Şık ve profesyonel giyinin\r\n\r\n## Sık Sorulan Sorular\r\n\r\n### \"Kendinizden bahseder misiniz?\"\r\n- Kısa ve öz olun\r\n- Eğitim ve deneyimlerinize değinin\r\n- Neden bu pozisyona uygun olduğunuzu vurgulayın\r\n\r\n### \"Güçlü yönleriniz neler?\"\r\n- Pozisyonla ilgili güçlü yönlerinizi seçin\r\n- Somut örneklerle destekleyin\r\n\r\n### \"Zayıf yönleriniz?\"\r\n- Dürüst olun ama kendinizi kötülemeyin\r\n- Nasıl geliştirmeye çalıştığınızı anlatın\r\n\r\n### \"5 yıl sonra kendinizi nerede görüyorsunuz?\"\r\n- Kariyer hedeflerinizden bahsedin\r\n- Şirketle birlikte büyümek istediğinizi belirtin\r\n\r\n## Görüşme Sonrası\r\n- Teşekkür e-postası gönderin\r\n- Geri dönüş süresini sorun\r\n- Sabırlı olun",
                            ContentCategoryId = 2,
                            Slug = "is-gorusmesine-hazirlik",
                            Summary = "İş görüşmesinde başarılı olmanın püf noktaları. Sık sorulan sorular ve nasıl cevaplanır?",
                            Title = "İş Görüşmesine Hazırlık"
                        },
                        new
                        {
                            Id = 6,
                            Content = "# Staj ve İş Bulma Stratejileri\r\n\r\n## İş Arama Platformları\r\n1. **LinkedIn** - Profesyonel networking\r\n2. **Kariyer.net** - İş ilanları\r\n3. **SecretCV** - Anonim başvuru\r\n4. **GitHub Jobs** - Yazılım pozisyonları\r\n5. **AngelList** - Startup'lar\r\n\r\n## Networking İpuçları\r\n- LinkedIn profilinizi güncel tutun\r\n- Sektör etkinliklerine katılın\r\n- Üniversite mezunları ağınızı kullanın\r\n- Mentorluk programlarına başvurun\r\n\r\n## Staj Başvurusu\r\n- **Ne zaman başvurmalı?** \r\n  Yazın staj için 3-4 ay önce başlayın\r\n  \r\n- **Başvuru mektubu yazın**\r\n  Neden o şirkette çalışmak istediğinizi açıklayın\r\n\r\n- **Portföy hazırlayın**\r\n  GitHub projeleri, kişisel web sitesi\r\n\r\n## İlk İş İçin İpuçları\r\n- Maaş beklentinizi araştırın\r\n- Şirket kültürüne dikkat edin\r\n- Gelişim fırsatlarını değerlendirin\r\n- İlk işinizde 1-2 yıl kalın",
                            ContentCategoryId = 2,
                            Slug = "staj-is-bulma",
                            Summary = "İlk stajınızı veya işinizi nasıl bulursunuz? Hangi platformları kullanmalısınız? Networking nasıl yapılır?",
                            Title = "Staj ve İş Bulma Stratejileri"
                        });
                });

            modelBuilder.Entity("microbloom.Entities.ContentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Slug = "universiteye-hazirlik",
                            Title = "Üniversiteye Hazırlık"
                        },
                        new
                        {
                            Id = 2,
                            Slug = "profesyonel-hayat",
                            Title = "İlk İşim ve Profesyonel Hayat"
                        });
                });

            modelBuilder.Entity("microbloom.Entities.CvSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileDownloadUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CvSamples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Üniversiteden yeni mezun olan bilgisayar mühendisleri için hazırlanmış profesyonel CV örneği.",
                            FileDownloadUrl = "/samples/cv-bilgisayar-yeni-mezun.pdf",
                            Title = "Yeni Mezun Bilgisayar Mühendisi CV Örneği"
                        },
                        new
                        {
                            Id = 2,
                            Description = "3-5 yıl deneyime sahip yazılım geliştiriciler için CV şablonu.",
                            FileDownloadUrl = "/samples/cv-yazilim-deneyimli.pdf",
                            Title = "Deneyimli Yazılım Geliştirici CV Örneği"
                        },
                        new
                        {
                            Id = 3,
                            Description = "İşletme bölümü mezunları için staj başvurularında kullanılabilecek CV örneği.",
                            FileDownloadUrl = "/samples/cv-isletme-stajyer.pdf",
                            Title = "İşletme Mezunu Stajyer CV Örneği"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mühendislik öğrencileri için hazırlanmış staj başvuru CV'si.",
                            FileDownloadUrl = "/samples/cv-muhendislik-staj.pdf",
                            Title = "Mühendislik Öğrencisi Staj CV Örneği"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Orta ve üst düzey yönetici pozisyonları için profesyonel CV şablonu.",
                            FileDownloadUrl = "/samples/cv-yonetici.pdf",
                            Title = "Yönetici Pozisyonu CV Örneği"
                        });
                });

            modelBuilder.Entity("microbloom.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastYearBaseRanking")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LastYearBaseScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UniversityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastYearBaseRanking = 1250,
                            LastYearBaseScore = 525.5,
                            Name = "Bilgisayar Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 2,
                            LastYearBaseRanking = 1580,
                            LastYearBaseScore = 520.29999999999995,
                            Name = "Elektrik-Elektronik Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 3,
                            LastYearBaseRanking = 2100,
                            LastYearBaseScore = 515.79999999999995,
                            Name = "Makine Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 4,
                            LastYearBaseRanking = 980,
                            LastYearBaseScore = 530.20000000000005,
                            Name = "Bilgisayar Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 5,
                            LastYearBaseRanking = 3200,
                            LastYearBaseScore = 495.5,
                            Name = "İşletme",
                            ScoreType = "EA",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 6,
                            LastYearBaseRanking = 4500,
                            LastYearBaseScore = 485.30000000000001,
                            Name = "Psikoloji",
                            ScoreType = "EA",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 7,
                            LastYearBaseRanking = 1100,
                            LastYearBaseScore = 528.70000000000005,
                            Name = "Bilgisayar Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 8,
                            LastYearBaseRanking = 1850,
                            LastYearBaseScore = 518.20000000000005,
                            Name = "Endüstri Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 9,
                            LastYearBaseRanking = 1450,
                            LastYearBaseScore = 522.5,
                            Name = "Bilgisayar Bilimi ve Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 10,
                            LastYearBaseRanking = 2350,
                            LastYearBaseScore = 512.29999999999995,
                            Name = "Endüstri Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 11,
                            LastYearBaseRanking = 1320,
                            LastYearBaseScore = 524.79999999999995,
                            Name = "Bilgisayar Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 12,
                            LastYearBaseRanking = 3800,
                            LastYearBaseScore = 490.19999999999999,
                            Name = "İşletme",
                            ScoreType = "EA",
                            UniversityId = 5
                        });
                });

            modelBuilder.Entity("microbloom.Entities.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobPostingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("JobPostingId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("microbloom.Entities.JobPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobPostings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 2,
                            Description = "ASP.NET Core ve Azure konusunda deneyimli...",
                            IsActive = true,
                            Location = "İstanbul",
                            PostedDate = new DateTime(2025, 11, 9, 0, 55, 44, 856, DateTimeKind.Utc).AddTicks(4463),
                            Title = "Kıdemli .NET Geliştiricisi"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Description = "React ve TypeScript bilen...",
                            IsActive = true,
                            Location = "Ankara",
                            PostedDate = new DateTime(2025, 11, 9, 0, 55, 44, 856, DateTimeKind.Utc).AddTicks(4465),
                            Title = "Frontend Geliştirici (React)"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            Description = "CI/CD süreçlerine hakim...",
                            IsActive = true,
                            Location = "İstanbul",
                            PostedDate = new DateTime(2025, 11, 9, 0, 55, 44, 856, DateTimeKind.Utc).AddTicks(4466),
                            Title = "DevOps Mühendisi"
                        });
                });

            modelBuilder.Entity("microbloom.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStateUniversity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebSite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İstanbul",
                            IsStateUniversity = true,
                            Name = "İstanbul Teknik Üniversitesi",
                            WebSite = "https://itu.edu.tr"
                        },
                        new
                        {
                            Id = 2,
                            City = "İstanbul",
                            IsStateUniversity = true,
                            Name = "Boğaziçi Üniversitesi",
                            WebSite = "https://boun.edu.tr"
                        },
                        new
                        {
                            Id = 3,
                            City = "Ankara",
                            IsStateUniversity = true,
                            Name = "Orta Doğu Teknik Üniversitesi",
                            WebSite = "https://metu.edu.tr"
                        },
                        new
                        {
                            Id = 4,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "Sabancı Üniversitesi",
                            WebSite = "https://sabanciuniv.edu"
                        },
                        new
                        {
                            Id = 5,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "Koç Üniversitesi",
                            WebSite = "https://ku.edu.tr"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("microbloom.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("microbloom.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("microbloom.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("microbloom.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("microbloom.Entities.AppUser", b =>
                {
                    b.HasOne("microbloom.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("microbloom.Entities.ContentArticle", b =>
                {
                    b.HasOne("microbloom.Entities.ContentCategory", "ContentCategory")
                        .WithMany("Articles")
                        .HasForeignKey("ContentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentCategory");
                });

            modelBuilder.Entity("microbloom.Entities.Department", b =>
                {
                    b.HasOne("microbloom.Entities.University", "University")
                        .WithMany("Departments")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("microbloom.Entities.JobApplication", b =>
                {
                    b.HasOne("microbloom.Entities.AppUser", "AppUser")
                        .WithMany("Applications")
                        .HasForeignKey("AppUserId");

                    b.HasOne("microbloom.Entities.JobPosting", "JobPosting")
                        .WithMany()
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("microbloom.Entities.JobPosting", b =>
                {
                    b.HasOne("microbloom.Entities.Company", "Company")
                        .WithMany("JobPostings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("microbloom.Entities.AppUser", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("microbloom.Entities.Company", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("microbloom.Entities.ContentCategory", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("microbloom.Entities.University", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
