// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using microbloom.Data;

#nullable disable

namespace microbloom.Migrations
{
    [DbContext(typeof(KariyerDBContext))]
    [Migration("20251109004944_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("microbloom.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("microbloom.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Global teknoloji lideri.",
                            LogoUrl = "google.png",
                            Name = "Google"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Yazılım ve bulut çözümleri.",
                            LogoUrl = "microsoft.png",
                            Name = "Microsoft"
                        });
                });

            modelBuilder.Entity("microbloom.Entities.ContentArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentCategoryId");

                    b.ToTable("ContentArticles");
                });

            modelBuilder.Entity("microbloom.Entities.ContentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContentCategories");
                });

            modelBuilder.Entity("microbloom.Entities.CvSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileDownloadUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CvSamples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Üniversiteden yeni mezun olan bilgisayar mühendisleri için hazırlanmış profesyonel CV örneği.",
                            FileDownloadUrl = "/samples/cv-bilgisayar-yeni-mezun.pdf",
                            Title = "Yeni Mezun Bilgisayar Mühendisi CV Örneği"
                        },
                        new
                        {
                            Id = 2,
                            Description = "3-5 yıl deneyime sahip yazılım geliştiriciler için CV şablonu.",
                            FileDownloadUrl = "/samples/cv-yazilim-deneyimli.pdf",
                            Title = "Deneyimli Yazılım Geliştirici CV Örneği"
                        },
                        new
                        {
                            Id = 3,
                            Description = "İşletme bölümü mezunları için staj başvurularında kullanılabilecek CV örneği.",
                            FileDownloadUrl = "/samples/cv-isletme-stajyer.pdf",
                            Title = "İşletme Mezunu Stajyer CV Örneği"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mühendislik öğrencileri için hazırlanmış staj başvuru CV'si.",
                            FileDownloadUrl = "/samples/cv-muhendislik-staj.pdf",
                            Title = "Mühendislik Öğrencisi Staj CV Örneği"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Orta ve üst düzey yönetici pozisyonları için profesyonel CV şablonu.",
                            FileDownloadUrl = "/samples/cv-yonetici.pdf",
                            Title = "Yönetici Pozisyonu CV Örneği"
                        });
                });

            modelBuilder.Entity("microbloom.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastYearBaseRanking")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LastYearBaseScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UniversityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastYearBaseRanking = 1250,
                            LastYearBaseScore = 525.5,
                            Name = "Bilgisayar Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 2,
                            LastYearBaseRanking = 1580,
                            LastYearBaseScore = 520.29999999999995,
                            Name = "Elektrik-Elektronik Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 3,
                            LastYearBaseRanking = 2100,
                            LastYearBaseScore = 515.79999999999995,
                            Name = "Makine Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 4,
                            LastYearBaseRanking = 980,
                            LastYearBaseScore = 530.20000000000005,
                            Name = "Bilgisayar Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 5,
                            LastYearBaseRanking = 3200,
                            LastYearBaseScore = 495.5,
                            Name = "İşletme",
                            ScoreType = "EA",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 6,
                            LastYearBaseRanking = 4500,
                            LastYearBaseScore = 485.30000000000001,
                            Name = "Psikoloji",
                            ScoreType = "EA",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 7,
                            LastYearBaseRanking = 1100,
                            LastYearBaseScore = 528.70000000000005,
                            Name = "Bilgisayar Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 8,
                            LastYearBaseRanking = 1850,
                            LastYearBaseScore = 518.20000000000005,
                            Name = "Endüstri Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 9,
                            LastYearBaseRanking = 1450,
                            LastYearBaseScore = 522.5,
                            Name = "Bilgisayar Bilimi ve Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 10,
                            LastYearBaseRanking = 2350,
                            LastYearBaseScore = 512.29999999999995,
                            Name = "Endüstri Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 11,
                            LastYearBaseRanking = 1320,
                            LastYearBaseScore = 524.79999999999995,
                            Name = "Bilgisayar Mühendisliği",
                            ScoreType = "SAY",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 12,
                            LastYearBaseRanking = 3800,
                            LastYearBaseScore = 490.19999999999999,
                            Name = "İşletme",
                            ScoreType = "EA",
                            UniversityId = 5
                        });
                });

            modelBuilder.Entity("microbloom.Entities.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobPostingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("JobPostingId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("microbloom.Entities.JobPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobPostings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 2,
                            Description = "ASP.NET Core ve Azure konusunda deneyimli...",
                            IsActive = true,
                            Location = "İstanbul",
                            PostedDate = new DateTime(2025, 11, 9, 0, 49, 44, 367, DateTimeKind.Utc).AddTicks(9939),
                            Title = "Kıdemli .NET Geliştiricisi"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Description = "React ve TypeScript bilen...",
                            IsActive = true,
                            Location = "Ankara",
                            PostedDate = new DateTime(2025, 11, 9, 0, 49, 44, 367, DateTimeKind.Utc).AddTicks(9942),
                            Title = "Frontend Geliştirici (React)"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            Description = "CI/CD süreçlerine hakim...",
                            IsActive = true,
                            Location = "İstanbul",
                            PostedDate = new DateTime(2025, 11, 9, 0, 49, 44, 367, DateTimeKind.Utc).AddTicks(9984),
                            Title = "DevOps Mühendisi"
                        });
                });

            modelBuilder.Entity("microbloom.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStateUniversity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebSite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İstanbul",
                            IsStateUniversity = true,
                            Name = "İstanbul Teknik Üniversitesi",
                            WebSite = "https://itu.edu.tr"
                        },
                        new
                        {
                            Id = 2,
                            City = "İstanbul",
                            IsStateUniversity = true,
                            Name = "Boğaziçi Üniversitesi",
                            WebSite = "https://boun.edu.tr"
                        },
                        new
                        {
                            Id = 3,
                            City = "Ankara",
                            IsStateUniversity = true,
                            Name = "Orta Doğu Teknik Üniversitesi",
                            WebSite = "https://metu.edu.tr"
                        },
                        new
                        {
                            Id = 4,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "Sabancı Üniversitesi",
                            WebSite = "https://sabanciuniv.edu"
                        },
                        new
                        {
                            Id = 5,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "Koç Üniversitesi",
                            WebSite = "https://ku.edu.tr"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("microbloom.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("microbloom.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("microbloom.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("microbloom.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("microbloom.Entities.AppUser", b =>
                {
                    b.HasOne("microbloom.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("microbloom.Entities.ContentArticle", b =>
                {
                    b.HasOne("microbloom.Entities.ContentCategory", "ContentCategory")
                        .WithMany("Articles")
                        .HasForeignKey("ContentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentCategory");
                });

            modelBuilder.Entity("microbloom.Entities.Department", b =>
                {
                    b.HasOne("microbloom.Entities.University", "University")
                        .WithMany("Departments")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("microbloom.Entities.JobApplication", b =>
                {
                    b.HasOne("microbloom.Entities.AppUser", "AppUser")
                        .WithMany("Applications")
                        .HasForeignKey("AppUserId");

                    b.HasOne("microbloom.Entities.JobPosting", "JobPosting")
                        .WithMany()
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("microbloom.Entities.JobPosting", b =>
                {
                    b.HasOne("microbloom.Entities.Company", "Company")
                        .WithMany("JobPostings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("microbloom.Entities.AppUser", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("microbloom.Entities.Company", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("microbloom.Entities.ContentCategory", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("microbloom.Entities.University", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
