// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using microbloom.Data;

#nullable disable

namespace microbloom.Migrations
{
    [DbContext(typeof(KariyerDBContext))]
    [Migration("20251109151511_AddAllTurkishUniversities")]
    partial class AddAllTurkishUniversities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("microbloom.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("microbloom.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Global teknoloji lideri.",
                            LogoUrl = "google.png",
                            Name = "Google"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Yazılım ve bulut çözümleri.",
                            LogoUrl = "microsoft.png",
                            Name = "Microsoft"
                        });
                });

            modelBuilder.Entity("microbloom.Entities.ContentArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentCategoryId");

                    b.ToTable("ContentArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "# &#x1F393; Üniversite Seçimi Rehberi\r\n\r\nÜniversite seçimi, hayatınızın en önemli kararlarından biridir. İşte doğru tercih yapmanız için ipuçları:\r\n\r\n## &#x1F4D6; 1. Bölüm Seçimi\r\n- &#x2714; İlgi alanlarınızı ve yeteneklerinizi değerlendirin\r\n- &#x2714; Bölümün kariyer olanaklarını araştırın\r\n- &#x2714; Sektördeki iş imkanlarını inceleyin\r\n\r\n## &#x1F3EB; 2. Üniversite Kriterleri\r\n- &#x1F4DA; Akademik kadro kalitesi\r\n- &#x1F3C6; Kampüs imkanları ve sosyal aktiviteler\r\n- &#x1F30D; Uluslararası değişim programları\r\n- &#x1F4BC; Mezun memnuniyeti ve kariyer desteği\r\n\r\n## &#x1F3D9; 3. Şehir Seçimi\r\n- &#x1F4B5; Yaşam maliyeti\r\n- &#x1F3AD; Kültürel ve sosyal olanaklar\r\n- &#x1F3E2; İş bulma imkanları\r\n- &#x1F3E0; Ailenize uzaklık\r\n\r\n## &#x1F4CA; 4. Taban Puan ve Sıralama\r\n- &#x2705; Gerçekçi hedefler belirleyin\r\n- &#x1F4DD; Yedek tercihlerinizi mutlaka doldurun\r\n- &#x1F4C8; Önceki yılların yerleştirme puanlarını inceleyin",
                            ContentCategoryId = 1,
                            Slug = "universite-secimi-rehberi",
                            Summary = "Üniversite seçerken nelere dikkat etmelisiniz? Şehir, bölüm, taban puan ve kariyer hedeflerinize göre doğru tercih nasıl yapılır?",
                            Title = "Üniversite Seçimi Rehberi"
                        },
                        new
                        {
                            Id = 2,
                            Content = "# &#x1F4BB; Mühendislik Bölümleri Rehberi\r\n\r\n## &#x1F5A5; Bilgisayar Mühendisliği\r\nYazılım geliştirme, veri bilimi, yapay zeka gibi alanlarda çalışma fırsatı sunar.\r\n\r\n**Kariyer Alanları:**\r\n- &#x1F4BB; Yazılım Geliştirici\r\n- &#x1F4CA; Veri Analisti / Data Scientist\r\n- &#x1F3D7; Sistem Mimarı\r\n- &#x2699; DevOps Mühendisi\r\n\r\n**Başlangıç Maaşları:** &#x1F4B0; 25.000 - 40.000 TL\r\n\r\n## &#x26A1; Elektrik-Elektronik Mühendisliği\r\nElektronik sistemler, güç sistemleri, telekomünikasyon alanlarında uzmanlaşma.\r\n\r\n**Kariyer Alanları:**\r\n- &#x1F50C; Elektronik Tasarım Mühendisi\r\n- &#x1F4A1; Enerji Sistemleri Uzmanı\r\n- &#x1F4E1; Telekomünikasyon Mühendisi\r\n\r\n## &#x2699; Endüstri Mühendisliği\r\nÜretim süreçlerinin optimizasyonu, lojistik ve proje yönetimi.\r\n\r\n**Kariyer Alanları:**\r\n- &#x1F4C8; Proje Yöneticisi\r\n- &#x1F69A; Lojistik Uzmanı\r\n- &#x1F504; Süreç Geliştirme Mühendisi",
                            ContentCategoryId = 1,
                            Slug = "bolum-rehberi-muhendislik",
                            Summary = "Mühendislik bölümleri hakkında her şey: Hangi bölüm size uygun? Kariyer olanakları neler? Mezuniyet sonrası ne yapabilirsiniz?",
                            Title = "Bölüm Rehberi: Mühendislik"
                        },
                        new
                        {
                            Id = 3,
                            Content = "# &#x1F4B0; Burs ve Mali Destek Rehberi\r\n\r\n## &#x1F3DB; Devlet Bursu\r\n- &#x1F393; YÖK bursu\r\n- &#x1F3E0; Kredi Yurtlar Kurumu (KYK)\r\n- &#x1F3C6; Başarı bursu\r\n\r\n## &#x1F3E2; Özel Kuruluş Bursları\r\n- &#x1F4DA; Vakıf üniversiteleri tam burs programları\r\n- &#x1F4BC; Özel sektör şirket bursları (TÜBİTAK, TÜSİAD)\r\n- &#x1F3DB; Belediye bursları\r\n\r\n## &#x1F4DD; Başvuru İpuçları\r\n1. &#x1F4C5; Başvuru tarihlerini takip edin\r\n2. &#x1F4C4; Gereken belgeleri önceden hazırlayın\r\n3. &#x270D; Motivasyon mektubunuza özen gösterin\r\n4. &#x1F4E8; Birden fazla burs programına başvurun\r\n\r\n## &#x1F517; Önemli Linkler\r\n- turkiye.gov.tr/kyk-ogrenci-kredisi\r\n- yok.gov.tr",
                            ContentCategoryId = 1,
                            Slug = "burs-mali-destek",
                            Summary = "Üniversite eğitiminiz için burs ve mali destek alma yolları. Hangi kuruluşlar burs veriyor? Başvuru şartları neler?",
                            Title = "Burs ve Mali Destek İmkanları"
                        },
                        new
                        {
                            Id = 4,
                            Content = "# &#x1F4C4; CV Hazırlama Rehberi\r\n\r\n## &#x2705; CV'de Olması Gerekenler\r\n\r\n### 1. &#x1F464; Kişisel Bilgiler\r\n- &#x1F4DD; Ad Soyad\r\n- &#x1F4DE; İletişim Bilgileri (Telefon, E-posta)\r\n- &#x1F517; LinkedIn Profili\r\n- &#x1F4BB; GitHub (yazılımcılar için)\r\n\r\n### 2. &#x1F4AC; Özet\r\n2-3 cümlelik kısa bir özet ile kendinizi tanıtın.\r\n\r\n**Örnek:** \"Bilgisayar Mühendisliği mezunu, 2 yıllık web geliştirme deneyimi. React ve Node.js teknolojilerinde uzman.\"\r\n\r\n### 3. &#x1F393; Eğitim\r\n- &#x1F3DB; Üniversite adı ve bölüm\r\n- &#x1F4C5; Mezuniyet tarihi\r\n- &#x1F4CA; Not ortalaması (3.00 üzerindeyse)\r\n\r\n### 4. &#x1F4BC; İş Deneyimi\r\n- &#x1F3E2; Şirket adı ve pozisyon\r\n- &#x1F4C6; Çalışma tarihleri\r\n- &#x2705; Görev ve başarılarınız\r\n- &#x1F6E0; Kullandığınız teknolojiler\r\n\r\n### 5. &#x1F680; Projeler\r\n- &#x1F4BB; Kişisel veya okul projeleri\r\n- &#x1F310; Açık kaynak katkılarınız\r\n\r\n### 6. &#x2B50; Beceriler\r\n- &#x1F4DA; Programlama dilleri\r\n- &#x1F527; Araçlar ve teknolojiler\r\n- &#x1F30D; Yabancı dil seviyeleri\r\n\r\n## &#x1F4A1; CV Hazırlama İpuçları\r\n- &#x1F4C4; Maksimum 2 sayfa olmalı\r\n- &#x1F3AF; Özgeçmişinizi her pozisyon için özelleştirin\r\n- &#x1F4CA; Somut başarılarınızı sayılarla destekleyin\r\n- &#x2705; Yazım hatalarından kaçının",
                            ContentCategoryId = 2,
                            Slug = "cv-hazirlama-rehberi",
                            Summary = "Profesyonel bir CV nasıl hazırlanır? İşverenin dikkatini çekecek CV örnekleri ve ipuçları.",
                            Title = "CV Hazırlama Rehberi"
                        },
                        new
                        {
                            Id = 5,
                            Content = "# &#x1F3AF; İş Görüşmesine Hazırlık\r\n\r\n## &#x1F4C5; Görüşme Öncesi\r\n1. &#x1F50D; Şirket hakkında araştırma yapın\r\n2. &#x1F4DD; Pozisyon tanımını detaylı inceleyin\r\n3. &#x1F4AC; Kendinizi tanıtma pratiği yapın\r\n4. &#x1F454; Şık ve profesyonel giyinin\r\n\r\n## &#x2753; Sık Sorulan Sorular\r\n\r\n### \"Kendinizden bahseder misiniz?\"\r\n- &#x23F1; Kısa ve öz olun\r\n- &#x1F393; Eğitim ve deneyimlerinize değinin\r\n- &#x1F3AF; Neden bu pozisyona uygun olduğunuzu vurgulayın\r\n\r\n### \"Güçlü yönleriniz neler?\"\r\n- &#x1F4AA; Pozisyonla ilgili güçlü yönlerinizi seçin\r\n- &#x1F4A1; Somut örneklerle destekleyin\r\n\r\n### \"Zayıf yönleriniz?\"\r\n- &#x1F91D; Dürüst olun ama kendinizi kötülemeyin\r\n- &#x1F4C8; Nasıl geliştirmeye çalıştığınızı anlatın\r\n\r\n### \"5 yıl sonra kendinizi nerede görüyorsunuz?\"\r\n- &#x1F680; Kariyer hedeflerinizden bahsedin\r\n- &#x1F3E2; Şirketle birlikte büyümek istediğinizi belirtin\r\n\r\n## &#x1F4E7; Görüşme Sonrası\r\n- &#x1F64F; Teşekkür e-postası gönderin\r\n- &#x23F0; Geri dönüş süresini sorun\r\n- &#x1F9D8; Sabırlı olun",
                            ContentCategoryId = 2,
                            Slug = "is-gorusmesine-hazirlik",
                            Summary = "İş görüşmesinde başarılı olmanın püf noktaları. Sık sorulan sorular ve nasıl cevaplanır?",
                            Title = "İş Görüşmesine Hazırlık"
                        },
                        new
                        {
                            Id = 6,
                            Content = "# &#x1F680; Staj ve İş Bulma Stratejileri\r\n\r\n## &#x1F310; İş Arama Platformları\r\n1. **LinkedIn** - &#x1F465; Profesyonel networking\r\n2. **Kariyer.net** - &#x1F4BC; İş ilanları\r\n3. **SecretCV** - &#x1F575; Anonim başvuru\r\n4. **GitHub Jobs** - &#x1F4BB; Yazılım pozisyonları\r\n5. **AngelList** - &#x1F680; Startup'lar\r\n\r\n## &#x1F91D; Networking İpuçları\r\n- &#x1F4C8; LinkedIn profilinizi güncel tutun\r\n- &#x1F3AA; Sektör etkinliklerine katılın\r\n- &#x1F393; Üniversite mezunları ağınızı kullanın\r\n- &#x1F468;&#x1F3EB; Mentorluk programlarına başvurun\r\n\r\n## &#x1F4BC; Staj Başvurusu\r\n- **Ne zaman başvurmalı?** \r\n  &#x2600; Yazın staj için 3-4 ay önce başlayın\r\n  \r\n- **Başvuru mektubu yazın**\r\n  &#x270D; Neden o şirkette çalışmak istediğinizi açıklayın\r\n\r\n- **Portföy hazırlayın**\r\n  &#x1F4BB; GitHub projeleri, kişisel web sitesi\r\n\r\n## &#x1F3AF; İlk İş İçin İpuçları\r\n- &#x1F4B0; Maaş beklentinizi araştırın\r\n- &#x1F3E2; Şirket kültürüne dikkat edin\r\n- &#x1F4C8; Gelişim fırsatlarını değerlendirin\r\n- &#x23F3; İlk işinizde 1-2 yıl kalın",
                            ContentCategoryId = 2,
                            Slug = "staj-is-bulma",
                            Summary = "İlk stajınızı veya işinizi nasıl bulursunuz? Hangi platformları kullanmalısınız? Networking nasıl yapılır?",
                            Title = "Staj ve İş Bulma Stratejileri"
                        });
                });

            modelBuilder.Entity("microbloom.Entities.ContentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Slug = "universiteye-hazirlik",
                            Title = "Üniversiteye Hazırlık"
                        },
                        new
                        {
                            Id = 2,
                            Slug = "profesyonel-hayat",
                            Title = "İlk İşim ve Profesyonel Hayat"
                        });
                });

            modelBuilder.Entity("microbloom.Entities.CvSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileDownloadUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CvSamples");
                });

            modelBuilder.Entity("microbloom.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastYearBaseRanking")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LastYearBaseScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UniversityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("microbloom.Entities.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobPostingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("JobPostingId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("microbloom.Entities.JobPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobPostings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 2,
                            Description = "ASP.NET Core ve Azure konusunda deneyimli...",
                            IsActive = true,
                            Location = "İstanbul",
                            PostedDate = new DateTime(2025, 11, 9, 15, 15, 11, 499, DateTimeKind.Utc).AddTicks(9916),
                            Title = "Kıdemli .NET Geliştiricisi"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Description = "React ve TypeScript bilen...",
                            IsActive = true,
                            Location = "Ankara",
                            PostedDate = new DateTime(2025, 11, 9, 15, 15, 11, 499, DateTimeKind.Utc).AddTicks(9922),
                            Title = "Frontend Geliştirici (React)"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            Description = "CI/CD süreçlerine hakim...",
                            IsActive = true,
                            Location = "İstanbul",
                            PostedDate = new DateTime(2025, 11, 9, 15, 15, 11, 499, DateTimeKind.Utc).AddTicks(9922),
                            Title = "DevOps Mühendisi"
                        });
                });

            modelBuilder.Entity("microbloom.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStateUniversity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebSite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İstanbul",
                            IsStateUniversity = true,
                            Name = "İstanbul Üniversitesi",
                            WebSite = "https://istanbul.edu.tr"
                        },
                        new
                        {
                            Id = 2,
                            City = "İstanbul",
                            IsStateUniversity = true,
                            Name = "İstanbul Teknik Üniversitesi",
                            WebSite = "https://itu.edu.tr"
                        },
                        new
                        {
                            Id = 3,
                            City = "İstanbul",
                            IsStateUniversity = true,
                            Name = "Boğaziçi Üniversitesi",
                            WebSite = "https://boun.edu.tr"
                        },
                        new
                        {
                            Id = 4,
                            City = "İstanbul",
                            IsStateUniversity = true,
                            Name = "Marmara Üniversitesi",
                            WebSite = "https://marmara.edu.tr"
                        },
                        new
                        {
                            Id = 5,
                            City = "İstanbul",
                            IsStateUniversity = true,
                            Name = "Yıldız Teknik Üniversitesi",
                            WebSite = "https://yildiz.edu.tr"
                        },
                        new
                        {
                            Id = 6,
                            City = "İstanbul",
                            IsStateUniversity = true,
                            Name = "Galatasaray Üniversitesi",
                            WebSite = "https://gsu.edu.tr"
                        },
                        new
                        {
                            Id = 7,
                            City = "Ankara",
                            IsStateUniversity = true,
                            Name = "Ankara Üniversitesi",
                            WebSite = "https://ankara.edu.tr"
                        },
                        new
                        {
                            Id = 8,
                            City = "Ankara",
                            IsStateUniversity = true,
                            Name = "Orta Doğu Teknik Üniversitesi",
                            WebSite = "https://metu.edu.tr"
                        },
                        new
                        {
                            Id = 9,
                            City = "Ankara",
                            IsStateUniversity = true,
                            Name = "Hacettepe Üniversitesi",
                            WebSite = "https://hacettepe.edu.tr"
                        },
                        new
                        {
                            Id = 10,
                            City = "Ankara",
                            IsStateUniversity = true,
                            Name = "Gazi Üniversitesi",
                            WebSite = "https://gazi.edu.tr"
                        },
                        new
                        {
                            Id = 11,
                            City = "Ankara",
                            IsStateUniversity = true,
                            Name = "Ankara Yıldırım Beyazıt Üniversitesi",
                            WebSite = "https://ybu.edu.tr"
                        },
                        new
                        {
                            Id = 12,
                            City = "İzmir",
                            IsStateUniversity = true,
                            Name = "Ege Üniversitesi",
                            WebSite = "https://ege.edu.tr"
                        },
                        new
                        {
                            Id = 13,
                            City = "İzmir",
                            IsStateUniversity = true,
                            Name = "Dokuz Eylül Üniversitesi",
                            WebSite = "https://deu.edu.tr"
                        },
                        new
                        {
                            Id = 14,
                            City = "İzmir",
                            IsStateUniversity = true,
                            Name = "İzmir Yüksek Teknoloji Enstitüsü",
                            WebSite = "https://iyte.edu.tr"
                        },
                        new
                        {
                            Id = 15,
                            City = "İzmir",
                            IsStateUniversity = true,
                            Name = "İzmir Katip Çelebi Üniversitesi",
                            WebSite = "https://ikc.edu.tr"
                        },
                        new
                        {
                            Id = 16,
                            City = "Kayseri",
                            IsStateUniversity = true,
                            Name = "Erciyes Üniversitesi",
                            WebSite = "https://erciyes.edu.tr"
                        },
                        new
                        {
                            Id = 17,
                            City = "Konya",
                            IsStateUniversity = true,
                            Name = "Selçuk Üniversitesi",
                            WebSite = "https://selcuk.edu.tr"
                        },
                        new
                        {
                            Id = 18,
                            City = "Erzurum",
                            IsStateUniversity = true,
                            Name = "Atatürk Üniversitesi",
                            WebSite = "https://atauni.edu.tr"
                        },
                        new
                        {
                            Id = 19,
                            City = "Adana",
                            IsStateUniversity = true,
                            Name = "Çukurova Üniversitesi",
                            WebSite = "https://cu.edu.tr"
                        },
                        new
                        {
                            Id = 20,
                            City = "Antalya",
                            IsStateUniversity = true,
                            Name = "Akdeniz Üniversitesi",
                            WebSite = "https://akdeniz.edu.tr"
                        },
                        new
                        {
                            Id = 21,
                            City = "Samsun",
                            IsStateUniversity = true,
                            Name = "Ondokuz Mayıs Üniversitesi",
                            WebSite = "https://omu.edu.tr"
                        },
                        new
                        {
                            Id = 22,
                            City = "Trabzon",
                            IsStateUniversity = true,
                            Name = "Karadeniz Teknik Üniversitesi",
                            WebSite = "https://ktu.edu.tr"
                        },
                        new
                        {
                            Id = 23,
                            City = "Bursa",
                            IsStateUniversity = true,
                            Name = "Uludağ Üniversitesi",
                            WebSite = "https://uludag.edu.tr"
                        },
                        new
                        {
                            Id = 24,
                            City = "Eskişehir",
                            IsStateUniversity = true,
                            Name = "Anadolu Üniversitesi",
                            WebSite = "https://anadolu.edu.tr"
                        },
                        new
                        {
                            Id = 25,
                            City = "Denizli",
                            IsStateUniversity = true,
                            Name = "Pamukkale Üniversitesi",
                            WebSite = "https://pau.edu.tr"
                        },
                        new
                        {
                            Id = 26,
                            City = "Elazığ",
                            IsStateUniversity = true,
                            Name = "Fırat Üniversitesi",
                            WebSite = "https://firat.edu.tr"
                        },
                        new
                        {
                            Id = 27,
                            City = "Isparta",
                            IsStateUniversity = true,
                            Name = "Süleyman Demirel Üniversitesi",
                            WebSite = "https://sdu.edu.tr"
                        },
                        new
                        {
                            Id = 28,
                            City = "Gaziantep",
                            IsStateUniversity = true,
                            Name = "Gaziantep Üniversitesi",
                            WebSite = "https://gantep.edu.tr"
                        },
                        new
                        {
                            Id = 29,
                            City = "Sakarya",
                            IsStateUniversity = true,
                            Name = "Sakarya Üniversitesi",
                            WebSite = "https://sakarya.edu.tr"
                        },
                        new
                        {
                            Id = 30,
                            City = "Kocaeli",
                            IsStateUniversity = true,
                            Name = "Kocaeli Üniversitesi",
                            WebSite = "https://kocaeli.edu.tr"
                        },
                        new
                        {
                            Id = 31,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "Koç Üniversitesi",
                            WebSite = "https://ku.edu.tr"
                        },
                        new
                        {
                            Id = 32,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "Sabancı Üniversitesi",
                            WebSite = "https://sabanciuniv.edu"
                        },
                        new
                        {
                            Id = 33,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "Bahçeşehir Üniversitesi",
                            WebSite = "https://bahcesehir.edu.tr"
                        },
                        new
                        {
                            Id = 34,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "İstanbul Bilgi Üniversitesi",
                            WebSite = "https://bilgi.edu.tr"
                        },
                        new
                        {
                            Id = 35,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "Özyeğin Üniversitesi",
                            WebSite = "https://ozyegin.edu.tr"
                        },
                        new
                        {
                            Id = 36,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "Kadir Has Üniversitesi",
                            WebSite = "https://khas.edu.tr"
                        },
                        new
                        {
                            Id = 37,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "Yeditepe Üniversitesi",
                            WebSite = "https://yeditepe.edu.tr"
                        },
                        new
                        {
                            Id = 38,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "İstanbul Ticaret Üniversitesi",
                            WebSite = "https://ticaret.edu.tr"
                        },
                        new
                        {
                            Id = 39,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "İstanbul Kültür Üniversitesi",
                            WebSite = "https://iku.edu.tr"
                        },
                        new
                        {
                            Id = 40,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "Işık Üniversitesi",
                            WebSite = "https://isikun.edu.tr"
                        },
                        new
                        {
                            Id = 41,
                            City = "Ankara",
                            IsStateUniversity = false,
                            Name = "Bilkent Üniversitesi",
                            WebSite = "https://bilkent.edu.tr"
                        },
                        new
                        {
                            Id = 42,
                            City = "Ankara",
                            IsStateUniversity = false,
                            Name = "Atılım Üniversitesi",
                            WebSite = "https://atilim.edu.tr"
                        },
                        new
                        {
                            Id = 43,
                            City = "Ankara",
                            IsStateUniversity = false,
                            Name = "Başkent Üniversitesi",
                            WebSite = "https://baskent.edu.tr"
                        },
                        new
                        {
                            Id = 44,
                            City = "Ankara",
                            IsStateUniversity = false,
                            Name = "Çankaya Üniversitesi",
                            WebSite = "https://cankaya.edu.tr"
                        },
                        new
                        {
                            Id = 45,
                            City = "Ankara",
                            IsStateUniversity = false,
                            Name = "TOBB Ekonomi ve Teknoloji Üniversitesi",
                            WebSite = "https://etu.edu.tr"
                        },
                        new
                        {
                            Id = 46,
                            City = "İzmir",
                            IsStateUniversity = false,
                            Name = "İzmir Ekonomi Üniversitesi",
                            WebSite = "https://ieu.edu.tr"
                        },
                        new
                        {
                            Id = 47,
                            City = "İzmir",
                            IsStateUniversity = false,
                            Name = "Yaşar Üniversitesi",
                            WebSite = "https://yasar.edu.tr"
                        },
                        new
                        {
                            Id = 48,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "Özyeğin Üniversitesi",
                            WebSite = "https://ozyegin.edu.tr"
                        },
                        new
                        {
                            Id = 49,
                            City = "Ankara",
                            IsStateUniversity = false,
                            Name = "TED Üniversitesi",
                            WebSite = "https://tedu.edu.tr"
                        },
                        new
                        {
                            Id = 50,
                            City = "İstanbul",
                            IsStateUniversity = false,
                            Name = "MEF Üniversitesi",
                            WebSite = "https://mef.edu.tr"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("microbloom.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("microbloom.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("microbloom.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("microbloom.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("microbloom.Entities.AppUser", b =>
                {
                    b.HasOne("microbloom.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("microbloom.Entities.ContentArticle", b =>
                {
                    b.HasOne("microbloom.Entities.ContentCategory", "ContentCategory")
                        .WithMany("Articles")
                        .HasForeignKey("ContentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentCategory");
                });

            modelBuilder.Entity("microbloom.Entities.Department", b =>
                {
                    b.HasOne("microbloom.Entities.University", "University")
                        .WithMany("Departments")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("microbloom.Entities.JobApplication", b =>
                {
                    b.HasOne("microbloom.Entities.AppUser", "AppUser")
                        .WithMany("Applications")
                        .HasForeignKey("AppUserId");

                    b.HasOne("microbloom.Entities.JobPosting", "JobPosting")
                        .WithMany()
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("microbloom.Entities.JobPosting", b =>
                {
                    b.HasOne("microbloom.Entities.Company", "Company")
                        .WithMany("JobPostings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("microbloom.Entities.AppUser", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("microbloom.Entities.Company", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("microbloom.Entities.ContentCategory", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("microbloom.Entities.University", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
